// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtiuz1Gl_Zr6bdKGxmKJ_s42ea5PVlUDo',
    appId: '1:175479000729:web:1fecc35b22f88231f5b208',
    messagingSenderId: '175479000729',
    projectId: 'coffee-house-12924',
    authDomain: 'coffee-house-12924.firebaseapp.com',
    storageBucket: 'coffee-house-12924.appspot.com',
    measurementId: 'G-VCQ4347YBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6cLEXLe_glVx7szct-5MJcX0bh6wUnJ4',
    appId: '1:175479000729:android:f7af3067298c6bfff5b208',
    messagingSenderId: '175479000729',
    projectId: 'coffee-house-12924',
    storageBucket: 'coffee-house-12924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQsi_atwQ_89SYWZEaIFP66sFJ8pPoJRg',
    appId: '1:175479000729:ios:6d7abd4c5532b818f5b208',
    messagingSenderId: '175479000729',
    projectId: 'coffee-house-12924',
    storageBucket: 'coffee-house-12924.appspot.com',
    iosBundleId: 'com.coffeehouse.coffeeHouse',
  );
}
